export const mockInsurances = [
  {
    id: 1,
    name: "Health Guard Gold",
    company: "ABC Insurance",
    type: "Health Insurance",
    description: "Comprehensive health coverage with no claim bonus",
    premium: 15000,
    trending: "Most Popular",
    agentCommission: "15%",
    claims: "98% Settlement Rate",
    benefits: [
      "Cashless Treatment",
      "No Claim Bonus",
      "Pre-existing Disease Cover",
      "Day Care Procedures",
      "Annual Health Check-up",
    ],
    coverage: "₹5 Lakhs - ₹50 Lakhs",
    premiumRange: "₹12,000 - ₹45,000 per year",
    features: {
      "Waiting Period": "2 years for pre-existing diseases",
      "Co-payment": "10% for specified treatments",
      "Room Rent Limit": "No capping",
      "Pre & Post Hospitalization": "60 & 90 days respectively",
    },
    agentInfo: {
      "Commission Structure": "15% on first year premium",
      "Renewal Commission": "7.5% from second year onwards",
      "Special Bonuses": "Additional 5% on quarterly targets",
      "Training Support": "Comprehensive product training provided",
      "Marketing Materials": "Digital and print materials available",
    },
    businessMetrics: {
      "Claims Settlement Ratio": "98%",
      "Average Claim Processing Time": "3-5 working days",
      "Customer Satisfaction": "4.5/5",
      "Market Share": "15%",
      "Growth Rate": "25% YoY",
    },
    customerSegments: {
      "Age Group": "25-60 years",
      "Income Range": "5-15 LPA",
      "Preferred Occupation": "Salaried professionals",
      "Geographic Focus": "Tier 1 & 2 cities",
      "Risk Profile": "Low to Medium",
    },
    documents: ["Age Proof", "Identity Proof", "Address Proof", "Income Proof", "Medical Reports (if any)"],
  },
  {
    id: 2,
    name: "Family Floater Plus",
    company: "XYZ Insurance",
    type: "Family Health Insurance",
    description: "Complete family protection with maternity benefits",
    premium: 20000,
    trending: "Best Value",
    agentCommission: "18%",
    claims: "95% Settlement Rate",
    benefits: [
      "Family Coverage",
      "Maternity Benefits",
      "Annual Health Check-up",
      "Child Vaccination Cover",
      "Alternative Treatment Cover",
    ],
    coverage: "₹10 Lakhs - ₹1 Crore",
    premiumRange: "₹15,000 - ₹60,000 per year",
    features: {
      "Waiting Period": "3 years for maternity",
      "Co-payment": "None",
      "Room Rent Limit": "Single private room",
      "Pre & Post Hospitalization": "30 & 60 days respectively",
    },
    agentInfo: {
      "Commission Structure": "18% on first year premium",
      "Renewal Commission": "9% from second year onwards",
      "Special Bonuses": "Additional 3% on half-yearly targets",
      "Training Support": "Online and offline training sessions",
      "Marketing Materials": "Customizable digital templates",
    },
    businessMetrics: {
      "Claims Settlement Ratio": "95%",
      "Average Claim Processing Time": "4-6 working days",
      "Customer Satisfaction": "4.3/5",
      "Market Share": "12%",
      "Growth Rate": "30% YoY",
    },
    customerSegments: {
      "Age Group": "28-45 years",
      "Income Range": "8-20 LPA",
      "Preferred Occupation": "All professionals",
      "Geographic Focus": "Pan India",
      "Risk Profile": "Low to Medium",
    },
    documents: [
      "Age Proof",
      "Identity Proof",
      "Address Proof",
      "Income Proof",
      "Marriage Certificate",
      "Medical Reports (if any)",
    ],
  },
]
